on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

name: Check spelling

jobs:
    codespell:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: codespell-project/actions-codespell@master

